import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toast";
import SessionProviders from "./providers/SessionProvider";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${poppins.className} h-full dark antialiased`}>
      <body className="min-h-full flex flex-col">
        <SessionProviders>{children}</SessionProviders>
        <Toaster />
      </body>
    </html>
  );
}
